### ISSUE TITLE
Please add an explicit (FOSS) licence/license

### ISSUE THREAD

**Issue by shlomif** [fvictorio/vim-extract-variable#6]
See https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ.mdwn#i-want-to-release-my-code---which-open-source-licence-should-i-use

**Comment by fvictorio** [comment]
Thanks, I just added a `LICENSE` file. I'm not really sure what is the best option for vim plugins, so I just went with MIT. If you know better, please tell me.

**Comment by shlomif** [comment]
On Tue, 11 Sep 2018 15:39:59 -0700
Franco Victorio <notifications@github.com> wrote:

> Thanks, I just added a `LICENSE` file. I'm not really sure what is the best
> option for vim plugins, so I just went with MIT. If you know better, please
> tell me.
> 

IANAL, but mit should be good enough.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Perl Humour - http://perl-begin.org/humour/

Oh! I wish you could see the look on his face! Actually, I would have also
liked to see the look on his face, but just then I woke up from the dream.
    — http://www.shlomifish.org/humour/TheEnemy/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
